# Generated by Django 5.2.7 on 2025-10-14 16:25

import django.db.models.deletion
import journal.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tab',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='entry',
            name='review_notes',
        ),
        migrations.AddField(
            model_name='entry',
            name='approved_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Pending'), (2, 'Approved'), (3, 'Rejected')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='entry',
            name='submitted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='tabs',
            field=models.ManyToManyField(blank=True, related_name='entries', to='journal.tab'),
        ),
        migrations.AlterField(
            model_name='entryimage',
            name='image',
            field=models.ImageField(upload_to=journal.models.entry_image_path),
        ),
        migrations.AlterField(
            model_name='entryimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('MODERATOR', 'Moderator'), ('AUTHOR', 'Author'), ('SUBAUTHOR', 'Subauthor')], db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_orgs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tab',
            name='enabled',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='tab',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['org', 'status', '-created_at'], name='journal_ent_org_id_fdc58a_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['author', 'status', '-created_at'], name='journal_ent_author__ff09fb_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['org', 'role'], name='journal_mem_org_id_6a3b98_idx'),
        ),
        migrations.AddIndex(
            model_name='tab',
            index=models.Index(fields=['org', 'enabled', 'name'], name='journal_tab_org_id_288a7a_idx'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'org'), name='uniq_membership_user_org'),
        ),
        migrations.AddConstraint(
            model_name='tab',
            constraint=models.UniqueConstraint(fields=('org', 'slug'), name='uniq_tab_slug_per_org'),
        ),
        migrations.AddConstraint(
            model_name='tab',
            constraint=models.UniqueConstraint(fields=('org', 'name'), name='uniq_tab_name_per_org'),
        ),
        migrations.RemoveField(
            model_name='tab',
            name='sitewide',
        ),
    ]
