# Generated by Django 5.2.7 on 2025-10-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_invite_accepted_by_invite_delivery_invite_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_step',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
