# Generated by Django 5.2.7 on 2025-10-16 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_userprofile_about_me_userprofile_custom_fields_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileimage',
            options={'ordering': ['-is_primary', '-id']},
        ),
        migrations.AddField(
            model_name='profileimage',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profileimage',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('value', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('text', 'Text'), ('url', 'URL'), ('date', 'Date'), ('number', 'Number')], default='text', max_length=20)),
                ('visible', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_items', related_query_name='custom_item', to='journal.userprofile')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('handle', models.CharField(blank=True, max_length=120)),
                ('url', models.URLField(max_length=500)),
                ('visible', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='journal.userprofile')),
            ],
            options={
                'ordering': ['platform', 'handle'],
            },
        ),
        migrations.DeleteModel(
            name='ProfileSocial',
        ),
    ]
