# Generated by Django 5.2.7 on 2025-10-16 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_alter_profileimage_options_profileimage_is_primary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nicknames',
            field=models.TextField(blank=True, default=''),
        ),
    ]
